### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by ajitStephen** [projectestac/agora#115]
I am trying to follow [instructions](https://github.com/projectestac/agora/blob/master/INSTALL.txt) but there is no config directory at root of project.

I am just trying to use, **Àgora Nodes**.

**Comment by jordipsalvador** [comment]
> I am trying to follow [instructions](https://github.com/projectestac/agora/blob/master/INSTALL.txt) but there is no config directory at root of project.
> 
> I am just trying to use, **Àgora Nodes**.


Hello, if you need help to install Nodes we can help you through our web: jordipsalvador.info/sate or in our e-mail sate@jordipsavador.info

**Comment by toniginard** [comment]
Hi!

Installation instructions have been updated. If you are still interested, check them out. 


Best wishes,
Toni Ginard
